// Yangilangan noutbuklar ma'lumotlari
const laptopsData = {
    'asus-tuf-dash-yanvar': {
        name: 'Asus TUF DASH F15',
        processor: 'RYZEN 7-7735HS = CORE i7 13-avlod',
        processorDetails: '[3.20GHz ~ 4.70GHz] 8 yader 16 potok',
        ram: 'DDR5 16GB',
        graphics: 'Nvidia GeForce RTX 4060 8GB + AMD RADEON Graphics',
        storage: '512GB M.2 Nvme SSD',
        display: '15.6 2.5K WV 165Hz',
        warranty: '1 Oy',
        price: '819$',
        features: ['Tez protsessor', 'Kuchli videokarta', 'Ajoyib 165Hz displey', 'Klaviatura yoritgichi'],
        image: './Photo/Asus TUF DASH F15/Asus TUF DASH F15 (1).jpg',
        images: [
            './Photo/Asus TUF DASH F15/Asus TUF DASH F15 (1).jpg',
            './Photo/Asus TUF DASH F15/Asus TUF DASH F15 (2).jpg',
            './Photo/Asus TUF DASH F15/Asus TUF DASH F15 (3).jpg',
            './Photo/Asus TUF DASH F15/Asus TUF DASH F15 (4).jpg',
            './Photo/Asus TUF DASH F15/Asus TUF DASH F15 (5).jpg',
            './Photo/Asus TUF DASH F15/Asus TUF DASH F15 (6).jpg',
            './Photo/Asus TUF DASH F15/Asus TUF DASH F15 (7).jpg',
            './Photo/Asus TUF DASH F15/Asus TUF DASH F15 (8).jpg',
            './Photo/Asus TUF DASH F15/Asus TUF DASH F15 (9).jpg',
            './Photo/Asus TUF DASH F15/Asus TUF DASH F15 (10).jpg'
        ],
        status: 'available',
        month: '01',
        year: '2025',
        type: 'laptop',
        category: 'gaming'
    },
    'lenovo-legion-avgust': {
        name: 'Lenovo LEGION',
        processor: 'RYZEN 7-7735HS = CORE i7 13-avlod',
        processorDetails: '[3.20GHz ~ 4.70GHz] 8 yader 16 potok',
        ram: 'DDR5 16GB',
        graphics: 'Nvidia GeForce RTX 4060 8GB + AMD RADEON Graphics',
        storage: '512GB M.2 Nvme SSD',
        display: '15.6 2.5K WV 165Hz',
        warranty: '1 Oy',
        price: '819$',
        features: ['Tez protsessor', 'Kuchli videokarta', 'Ajoyib 165Hz displey', 'Klaviatura yoritgichi'],
        image: './Photo/Lenovo LEGION/lenova LEGION (1).jpg',
        images: [
            './Photo/Lenovo LEGION/lenova LEGION (1).jpg',
            './Photo/Lenovo LEGION/lenova LEGION (2).jpg',
            './Photo/Lenovo LEGION/lenova LEGION (3).jpg',
            './Photo/Lenovo LEGION/lenova LEGION (4).jpg',
            './Photo/Lenovo LEGION/lenova LEGION (5).jpg',
            './Photo/Lenovo LEGION/lenova LEGION (6).jpg',
            './Photo/Lenovo LEGION/lenova LEGION (7).jpg',
            './Photo/Lenovo LEGION/lenova LEGION (8).jpg',
            './Photo/Lenovo LEGION/lenova LEGION (9).jpg',
            './Photo/Lenovo LEGION/lenova LEGION (10).jpg'
        ],
        status: 'available',
        month: '08',
        year: '2025',
        type: 'laptop',
        category: 'gaming'
    },
    'macbook-air-fevral': {
        name: 'MacBook Air',
        processor: 'Apple M2 [2022]',
        processorDetails: 'Apple Silicon Chip',
        ram: 'DDR4 8GB',
        graphics: 'Apple M2 Integrated Graphics',
        storage: '256GB SSD',
        display: '13.3 [2560 × 1664]',
        warranty: '1 Oy',
        price: '649$',
        features: ['Barmoq izi', 'Klaviatura yoritgichi', 'Metall korpus', 'Batareya: 95% quvvat, 75 sikl'],
        image: './Photo/MacBook Air/MacBook Air (1).jpg',
        images: [
            './Photo/MacBook Air/MacBook Air (1).jpg',
            './Photo/MacBook Air/MacBook Air (2).jpg',
            './Photo/MacBook Air/MacBook Air (3).jpg',
            './Photo/MacBook Air/MacBook Air (4).jpg',
            './Photo/MacBook Air/MacBook Air (5).jpg',
            './Photo/MacBook Air/MacBook Air (6).jpg',
            './Photo/MacBook Air/MacBook Air (7).jpg',
            './Photo/MacBook Air/MacBook Air (8).jpg',
            './Photo/MacBook Air/MacBook Air (9).jpg',
            './Photo/MacBook Air/MacBook Air (10).jpg'
        ],
        status: 'available',
        month: '02',
        year: '2025',
        type: 'laptop',
        category: 'business'
    },
    'acer-aspire-yangi': {
        name: 'Acer ASPIRE',
        processor: 'CORE i5 - 1235U [ 12-avlod ]',
        processorDetails: '[3.30GHz ~ 4.40GHz] 10 yader 12 potok',
        ram: 'DDR4 8GB',
        graphics: 'Intel UHD Graphics',
        storage: '512GB M.2 Nvme SSD',
        display: '15.6 FULL HD',
        warranty: '1 Yil',
        price: '369$',
        features: ['Dastlabki qadoqda', 'YANGI', '1 yil kafolat', 'Intel 12-avlod'],
        image: './Photo/Acer ASPIRE/Acer ASPIRE (1).jpg',
        images: [
            './Photo/Acer ASPIRE/Acer ASPIRE (1).jpg',
            './Photo/Acer ASPIRE/Acer ASPIRE (2).jpg',
            './Photo/Acer ASPIRE/Acer ASPIRE (3).jpg',
            './Photo/Acer ASPIRE/Acer ASPIRE (4).jpg',
            './Photo/Acer ASPIRE/Acer ASPIRE (5).jpg',
            './Photo/Acer ASPIRE/Acer ASPIRE (6).jpg',
            './Photo/Acer ASPIRE/Acer ASPIRE (7).jpg',
            './Photo/Acer ASPIRE/Acer ASPIRE (8).jpg',
            './Photo/Acer ASPIRE/Acer ASPIRE (9).jpg'
        ],
        status: 'available',
        month: '08',
        year: '2024',
        type: 'laptop',
        category: 'student'
    },
    'macbook-pro-mart': {
        name: 'MacBook Pro',
        processor: 'Apple M2 [2022]',
        processorDetails: 'Apple Silicon Chip',
        ram: 'DDR4 8GB',
        graphics: 'Apple M2 Integrated Graphics',
        storage: '256GB SSD',
        display: '13.3 [2560 × 1600]',
        warranty: '1 Oy',
        price: '699$',
        features: ['Barmoq izi', 'Klaviatura yoritgichi', 'Metall korpus', 'Batareya: 96% quvvat, 46 sikl'],
        image: './Photo/MacBook Pro/MacBook Pro (1).jpg',
        images: [
            './Photo/MacBook Pro/MacBook Pro (1).jpg',
            './Photo/MacBook Pro/MacBook Pro (2).jpg',
            './Photo/MacBook Pro/MacBook Pro (3).jpg',
            './Photo/MacBook Pro/MacBook Pro (4).jpg',
            './Photo/MacBook Pro/MacBook Pro (5).jpg',
            './Photo/MacBook Pro/MacBook Pro (6).jpg',
            './Photo/MacBook Pro/MacBook Pro (7).jpg',
            './Photo/MacBook Pro/MacBook Pro (8).jpg',
            './Photo/MacBook Pro/MacBook Pro (9).jpg',
            './Photo/MacBook Pro/MacBook Pro (10).jpg'
        ],
        status: 'available',
        month: '03',
        year: '2025',
        type: 'laptop',
        category: 'business'
    },
    'hp-pavilion-aprel': {
        name: 'HP Pavilion',
        processor: 'RYZEN 5 5500U = CORE i5 11-avlod',
        processorDetails: '[2.10GHz ~ 4.0GHz] 6 yader 12 potok',
        ram: 'DDR4 8GB',
        graphics: 'AMD RADEON Graphics',
        storage: '256GB M.2 Nvme SSD',
        display: '15.6 Full HD IPS',
        warranty: '1 Oy',
        price: '299$',
        features: ['Klaviatura yoritgichi', 'Metall korpus'],
        image: './Photo/HP Pavilion/HP Pavilion  (1).jpg',
        images: [
            './Photo/HP Pavilion/HP Pavilion  (1).jpg',
            './Photo/HP Pavilion/HP Pavilion  (2).jpg',
            './Photo/HP Pavilion/HP Pavilion  (3).jpg',
            './Photo/HP Pavilion/HP Pavilion  (4).jpg',
            './Photo/HP Pavilion/HP Pavilion  (5).jpg',
            './Photo/HP Pavilion/HP Pavilion  (6).jpg',
            './Photo/HP Pavilion/HP Pavilion  (7).jpg',
            './Photo/HP Pavilion/HP Pavilion  (8).jpg',
            './Photo/HP Pavilion/HP Pavilion  (9).jpg',
            './Photo/HP Pavilion/HP Pavilion  (10).jpg'
        ],
        status: 'available',
        month: '04',
        year: '2025',
        type: 'laptop',
        category: 'student'
    },
    'msi-katana-may': {
        name: 'MSI KATANA 17',
        processor: 'CORE i7 - 13620H [13-avlod]',
        processorDetails: '[2.40GHz ~ 5.10GHz] 10 yader 16 potok',
        ram: 'DDR5 16GB',
        graphics: 'Intel UHD Graphics + Nvidia GeForce RTX 4060 8GB',
        storage: '512GB M.2 Nvme SSD',
        display: '17.3 FULL HD IPS 144Hz',
        warranty: '1 Oy',
        price: '749$',
        features: ['Tez protsessor', 'Kuchli videokarta', 'Klaviatura yoritgichi', 'Ajoyib 144Hz displey'],
        image: './Photo/Msi KATANA 17/Msi KATANA 17 (1).jpg',
        images: [
            './Photo/Msi KATANA 17/Msi KATANA 17 (1).jpg',
            './Photo/Msi KATANA 17/Msi KATANA 17 (2).jpg',
            './Photo/Msi KATANA 17/Msi KATANA 17 (3).jpg',
            './Photo/Msi KATANA 17/Msi KATANA 17 (4).jpg',
            './Photo/Msi KATANA 17/Msi KATANA 17 (5).jpg',
            './Photo/Msi KATANA 17/Msi KATANA 17 (6).jpg',
            './Photo/Msi KATANA 17/Msi KATANA 17 (7).jpg',
            './Photo/Msi KATANA 17/Msi KATANA 17 (8).jpg',
            './Photo/Msi KATANA 17/Msi KATANA 17 (9).jpg',
            './Photo/Msi KATANA 17/Msi KATANA 17 (10).jpg'
        ],
        status: 'available',
        month: '05',
        year: '2025',
        type: 'laptop',
        category: 'gaming'
    },
    'asus-expertbook-iyun': {
        name: 'Asus ExpertBook X360',
        processor: 'CORE i5 - 1240P [12-avlod]',
        processorDetails: '[1.70GHz ~ 4.40GHz] 10 yader 12 potok',
        ram: 'DDR4 8GB',
        graphics: 'Intel UHD Graphics',
        storage: '256GB M.2 Nvme SSD',
        display: '15.6 FULL HD IPS Touchscreen',
        warranty: '1 Oy',
        price: '355$',
        features: ['Sensorli ekran', 'Metall korpus', 'Barmoq izi'],
        image: './Photo/Asus ExpertBook X360/Asus ExpertBook X360 (1).jpg',
        images: [
            './Photo/Asus ExpertBook X360/Asus ExpertBook X360 (1).jpg',
            './Photo/Asus ExpertBook X360/Asus ExpertBook X360 (2).jpg',
            './Photo/Asus ExpertBook X360/Asus ExpertBook X360 (3).jpg',
            './Photo/Asus ExpertBook X360/Asus ExpertBook X360 (4).jpg',
            './Photo/Asus ExpertBook X360/Asus ExpertBook X360 (5).jpg',
            './Photo/Asus ExpertBook X360/Asus ExpertBook X360 (6).jpg',
            './Photo/Asus ExpertBook X360/Asus ExpertBook X360 (7).jpg',
            './Photo/Asus ExpertBook X360/Asus ExpertBook X360 (8).jpg',
            './Photo/Asus ExpertBook X360/Asus ExpertBook X360 (9).jpg',
            './Photo/Asus ExpertBook X360/Asus ExpertBook X360 (10).jpg'
        ],
        status: 'available',
        month: '06',
        year: '2025',
        type: 'laptop',
        category: 'business'
    },
    'asus-rog-strix-iyul': {
        name: 'Asus ROG Strix',
        processor: 'RYZEN 7-6800H = CORE i7 12-avlod',
        processorDetails: '[3.20GHz ~ 4.70GHz] 8 yader 16 potok',
        ram: 'DDR5 16GB',
        graphics: 'Nvidia GeForce RTX 3050 4GB + AMD RADEON Graphics',
        storage: '512GB M.2 Nvme SSD',
        display: '15.6 Full HD WV 144Hz',
        warranty: '1 Oy',
        price: '669$',
        features: ['Tez protsessor', 'Kuchli videokarta', 'Ajoyib 144Hz displey', 'RGB klaviatura yoritgichi'],
        image: './Photo/Asus ROG Strix/Asus ROG Strix (1).jpg',
        images: [
            './Photo/Asus ROG Strix/Asus ROG Strix (1).jpg',
            './Photo/Asus ROG Strix/Asus ROG Strix (2).jpg',
            './Photo/Asus ROG Strix/Asus ROG Strix (3).jpg',
            './Photo/Asus ROG Strix/Asus ROG Strix (4).jpg',
            './Photo/Asus ROG Strix/Asus ROG Strix (5).jpg',
            './Photo/Asus ROG Strix/Asus ROG Strix (6).jpg',
            './Photo/Asus ROG Strix/Asus ROG Strix (7).jpg',
            './Photo/Asus ROG Strix/Asus ROG Strix (8).jpg',
            './Photo/Asus ROG Strix/Asus ROG Strix (9).jpg',
            './Photo/Asus ROG Strix/Asus ROG Strix (10).jpg'
        ],
        status: 'available',
        month: '07',
        year: '2025',
        type: 'laptop',
        category: 'gaming'
    },
    'hp-avgust': {
        name: 'HP',
        processor: 'RYZEN 5 7520U = CORE i5 13-avlod',
        processorDetails: '[2.80GHz ~ 4.30GHz] 4 yader 8 potok',
        ram: 'DDR5 8GB',
        graphics: 'AMD RADEON Graphics',
        storage: '512GB M.2 Nvme SSD',
        display: '15.6 Full HD',
        warranty: '1 Oy',
        price: '315$',
        features: ['Tez protsessor', 'Yaxshi xotira', 'Full HD display'],
        image: './Photo/HP/HP (1).jpg',
        images: [
            './Photo/HP/HP (1).jpg',
            './Photo/HP/HP (2).jpg',
            './Photo/HP/HP (3).jpg',
            './Photo/HP/HP (4).jpg',
            './Photo/HP/HP (5).jpg',
            './Photo/HP/HP (6).jpg',
            './Photo/HP/HP (7).jpg',
            './Photo/HP/HP (8).jpg'
        ],
        status: 'available',
        month: '08',
        year: '2025',
        type: 'laptop',
        category: 'student'
    },
    'hp-envy-x360-avgust': {
        name: 'HP ENVY X360',
        processor: 'CORE i5 - 1335U [13-avlod]',
        processorDetails: '[1.30GHz ~ 4.60GHz] 10 yader 12 potok',
        ram: 'DDR4 8GB',
        graphics: 'Intel Iris Xe Graphics',
        storage: '512GB M.2 Nvme SSD',
        display: '14.0 Full HD IPS Touchscreen',
        warranty: '1 Oy',
        price: '399$',
        features: ['Sensorli ekran', 'Barmoq izi', 'Klaviatura yoritgichi', 'Metall korpus'],
        image: './Photo/HP ENVY X360/HP ENVY X360 (1).jpg',
        images: [
            './Photo/HP ENVY X360/HP ENVY X360 (1).jpg',
            './Photo/HP ENVY X360/HP ENVY X360 (2).jpg',
            './Photo/HP ENVY X360/HP ENVY X360 (3).jpg',
            './Photo/HP ENVY X360/HP ENVY X360 (4).jpg',
            './Photo/HP ENVY X360/HP ENVY X360 (5).jpg',
            './Photo/HP ENVY X360/HP ENVY X360 (6).jpg',
            './Photo/HP ENVY X360/HP ENVY X360 (7).jpg',
            './Photo/HP ENVY X360/HP ENVY X360 (8).jpg',
            './Photo/HP ENVY X360/HP ENVY X360 (9).jpg',
            './Photo/HP ENVY X360/HP ENVY X360 (10).jpg'
        ],
        status: 'available',
        month: '08',
        year: '2025',
        type: 'laptop',
        category: 'business'
    },
    'asus-vivobook-avgust': {
        name: 'Asus VivoBook',
        processor: 'Core i5 - 12500H [12-avlod]',
        processorDetails: '[2.50GHz ~ 4.50GHz] 8 yader 12 potok',
        ram: 'DDR4 8GB',
        graphics: 'Intel UHD Graphics',
        storage: '256GB M.2 Nvme SSD',
        display: '14.0 2.8K OLED 90Hz',
        warranty: '1 Oy',
        price: '379$',
        features: ['Tez protsessor', 'Klaviatura yoritgichi', 'Barmoq izi', 'Ajoyib OLED 90Hz displey'],
        image: './Photo/Asus VivoBook/Asus VivoBook  (1).jpg',
        images: [
            './Photo/Asus VivoBook/Asus VivoBook  (1).jpg',
            './Photo/Asus VivoBook/Asus VivoBook  (2).jpg',
            './Photo/Asus VivoBook/Asus VivoBook  (3).jpg',
            './Photo/Asus VivoBook/Asus VivoBook  (4).jpg',
            './Photo/Asus VivoBook/Asus VivoBook  (5).jpg',
            './Photo/Asus VivoBook/Asus VivoBook  (6).jpg',
            './Photo/Asus VivoBook/Asus VivoBook  (7).jpg',
            './Photo/Asus VivoBook/Asus VivoBook  (8).jpg',
            './Photo/Asus VivoBook/Asus VivoBook  (9).jpg',
            './Photo/Asus VivoBook/Asus VivoBook  (10).jpg'
        ],
        status: 'available',
        month: '08',
        year: '2025',
        type: 'laptop',
        category: 'student'
    },
    'hp-victus-avgust': {
        name: 'HP Victus',
        processor: 'Ryzen 5 7535HS = Core i5 13-avlod',
        processorDetails: '[3.30GHz ~ 4.50GHz] 6 yader 12 potok',
        ram: 'DDR5 8GB',
        graphics: 'AMD RADEON RX6550M 4GB + AMD RADEON Graphics',
        storage: '512GB M.2 Nvme SSD',
        display: '15.6 Full HD IPS 144Hz',
        warranty: '1 Oy',
        price: '449$',
        features: ['Kuchli protsessor', 'Tez ishlaydigan videokarta', 'Klaviatura yoritgichi', 'Ajoyib 144Hz displey'],
        image: './Photo/HP Victus/HP Victus (1).jpg',
        images: [
            './Photo/HP Victus/HP Victus (1).jpg',
            './Photo/HP Victus/HP Victus (2).jpg',
            './Photo/HP Victus/HP Victus (3).jpg',
            './Photo/HP Victus/HP Victus (4).jpg',
            './Photo/HP Victus/HP Victus (5).jpg',
            './Photo/HP Victus/HP Victus (6).jpg',
            './Photo/HP Victus/HP Victus (7).jpg',
            './Photo/HP Victus/HP Victus (8).jpg',
            './Photo/HP Victus/HP Victus (9).jpg',
            './Photo/HP Victus/HP Victus (10).jpg'
        ],
        status: 'available',
        month: '08',
        year: '2025',
        type: 'laptop',
        category: 'gaming',
        addedDate: new Date().toISOString()
    },
    'hp-ryzen5-5500u': {
        name: 'HP Ryzen 5 5500U',
        processor: 'RYZEN 5 5500U = CORE i5 11-avlod',
        processorDetails: '[2.10GHz ~ 4.0GHz] 6 yader 12 potok',
        ram: 'DDR4 8GB',
        graphics: 'AMD Radeon Graphics',
        storage: '256GB M.2 Nvme SSD',
        display: '15.6 Full HD IPS',
        warranty: '1 Oy',
        price: '259$',
        features: ['Yengil va portativ', 'Yaxshi ishlash', 'Full HD displey'],
        image: './Photo/HP1/HP1 (1).jpg',
        images: [
            './Photo/HP1/HP1 (1).jpg',
            './Photo/HP1/HP1 (2).jpg',
            './Photo/HP1/HP1 (3).jpg',
            './Photo/HP1/HP1 (4).jpg',
            './Photo/HP1/HP1 (5).jpg',
            './Photo/HP1/HP1 (6).jpg',
            './Photo/HP1/HP1 (7).jpg',
            './Photo/HP1/HP1 (8).jpg'
        ],
        status: 'available',
        month: '08',
        year: '2025',
        type: 'laptop',
        category: 'student',
        addedDate: new Date().toISOString()
    },
    'msi-thin-15': {
        name: 'MSI Thin 15',
        processor: 'Core i5 13420H [13-avlod]',
        processorDetails: '[2.10GHz ~ 4.60GHz] 8 yader 12 potok',
        ram: 'DDR4 16GB',
        graphics: 'Nvidia GeForce RTX 4060 8GB + Intel UHD Graphics',
        storage: '512GB Nvme SSD',
        display: '15.6 Full HD IPS 144Hz',
        warranty: '1 Oy',
        price: '649$',
        features: ['Kuchli protsessor', 'Tezkor ishlash', '144Hz ajoyib displey', 'Klaviatura yoritgichi'],
        image: './Photo/Msi Thin 15/Msi Thin 15 (1).jpg',
        images: [
            './Photo/Msi Thin 15/Msi Thin 15 (1).jpg',
            './Photo/Msi Thin 15/Msi Thin 15 (2).jpg',
            './Photo/Msi Thin 15/Msi Thin 15 (3).jpg',
            './Photo/Msi Thin 15/Msi Thin 15 (4).jpg',
            './Photo/Msi Thin 15/Msi Thin 15 (5).jpg',
            './Photo/Msi Thin 15/Msi Thin 15 (6).jpg',
            './Photo/Msi Thin 15/Msi Thin 15 (7).jpg',
            './Photo/Msi Thin 15/Msi Thin 15 (8).jpg',
            './Photo/Msi Thin 15/Msi Thin 15 (9).jpg',
            './Photo/Msi Thin 15/Msi Thin 15 (10).jpg'
        ],
        status: 'available',
        month: '08',
        year: '2025',
        type: 'laptop',
        category: 'gaming',
        addedDate: new Date().toISOString()
    },
    'hp-corei3-1115g4': {
        name: 'HP Core i3 1115G4',
        processor: 'CORE i3 - 1115G4 [11-avlod]',
        processorDetails: '[3.00GHz ~ 4.10GHz] 2 yader 4 potok',
        ram: 'DDR4 8GB',
        graphics: 'Intel UHD Graphics',
        storage: '256GB M.2 Nvme SSD',
        display: '15.6 Full HD',
        warranty: '1 Yil',
        price: '289$',
        features: [
            'YANGI',
            'Yengil va portativ',
            'Yangi karobkada',
            '1 yil kafolat',
            'Tezkor SSD xotira',
            'Karobkasi bor (YANGI)'
        ],
        image: './Photo/HP289/HP289 (1).jpg',
        images: [
            './Photo/HP289/HP289 (1).jpg',
            './Photo/HP289/HP289 (2).jpg',
            './Photo/HP289/HP289 (3).jpg',
            './Photo/HP289/HP289 (4).jpg',
            './Photo/HP289/HP289 (5).jpg',
            './Photo/HP289/HP289 (6).jpg',
            './Photo/HP289/HP289 (7).jpg',
            './Photo/HP289/HP289 (8).jpg'
        ],
        status: 'available',
        month: '08',
        year: '2025',
        type: 'laptop',
        category: 'student',
        addedDate: new Date().toISOString()
    }
};

// Desktop items array
const desktopItems = [
  {
    id: 'gaming-pc-setup',
    name: 'Gaming PC Setup',
    processor: 'Ryzen 7 8700F',
    processorDetails: '[4.0GHz ~ 5.0GHz] 8 yader 16 potok',
    motherboard: 'B650 AORUS DDR5',
    cooling: 'Gamemax X Trio Liquid❄️',
    ram: 'Kingston-fury 32GB RGB DDR5/6000Mhz❤️‍🔥',
    psu: 'Power-train 850W gold+',
    graphics: 'NVIDIA GeForce RTX 2060 8GB',
    storage: 'Samsung 512GB NVMe M.2 SSD',
    warranty: '6 oy',
    price: '949$',
    features: ['YANGI', '6 oy kafolat', 'Oʻyin kompyuteri'],
    image: './Photo/pckom/pckom (1).jpg',
    images: [
      './Photo/pckom/pckom (1).jpg',
      './Photo/pckom/pckom (5).jpg',
      './Photo/pckom/pckom (6).jpg',
      './Photo/pckom/pckom (7).jpg'
    ],
    status: 'available',
    type: 'desktop',
    category: 'gaming',
    month: '08',
    year: '2025',
    addedDate: new Date().toISOString()
  }
];
